name: Deploy

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  # needed for reading the OIDC token and assuming the role
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com
    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/search-production-github-actions
          role-session-name: GithubSearchDeploy
          aws-region: eu-west-1
      - uses: aws-actions/amazon-ecr-login@v2
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - uses: extractions/setup-just@v3
      - uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml
      - run: just build-image
      - run: just push-image
